from pybricks.parameters import Port

# SWERVE
SWERVE_LEFT_STEERING_PORT = Port.A
SWERVE_LEFT_DRIVING_PORT = Port.B
SWERVE_RIGHT_DRIVING_PORT = Port.C
SWERVE_LEFT_STEERING_PORT = Port.D

# DRIVE SENSORS

# CLAW
